spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-exam
    username: root
    password: Barnigtr12345xd
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create

app:
  rootPassword: admin